### ISSUE TITLE
C++ bindings don't have copy constructors and it causes crashes

### ISSUE THREAD

**Issue by Sixshaman** [KhronosGroup/SPIRV-Reflect#105]
This code works correctly:
`spv_reflect::ShaderModule shaderModule = spv_reflect::ShaderModule(vertexShaderData);`

This does not:
```
spv_reflect::ShaderModule shaderModule;
shaderModule = spv_reflect::ShaderModule(vertexShaderData);
```

The copy constructor and the assignment operator for `ShaderModule` are not defined, and the default ones simply copy the pointers. After the assignment the old copy of the object gets destroyed, freeing the memory and leaving dangling pointers in the second object.

**Comment by chaoticbob** [comment]
Thanks for reporting this. Unfortunately there's not an easy way to make the copy work currently since there's a bunch of pointers that would need to be updated to use offsets. I made `spv_reflect::ShaderModule` noncopyable (https://github.com/KhronosGroup/SPIRV-Reflect/commit/fcf82e41d15db90b1cec583c1f6913bec1a9dd84). Will have to revisit later to see what's involved in doing a full copy.
