### ISSUE TITLE
Mapping Spirv-reflect module to D3DReflect

### ISSUE THREAD

**Issue by sparkskapil** [KhronosGroup/SPIRV-Reflect#132]
I am working with DXVK, and need to convert the spirv-reflect module contents to D3DReflect.
Want to fill InputParameters, OutputParameters, ConstantBuffers, BoundResources.
Where can I find mapping for the spirv-reflect module to D3DReflect.

**Comment by chaoticbob** [comment]
There isn't a mapping because no one has requeested it in the past. I've never had any practical experience with D3DReflect so I'm not sure what the terminilogy is. However, assuming the concepts are similar here's some starting points.:
* Input/output shader variables are described by SpvReflectInterfaceVariable
  * There's an enumeration function for these
* Constant buffers and structured buffers are both described by SpvReflectBlockVariable
  * Structs have member variables that will need to be parsed hierarchically
* All resources are described by SpvReflectDescriptorBinding
  * There's an enumeration functio nfor these
