### ISSUE TITLE
VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER is detected as two descriptor set layouts: VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE and VK_DESCRIPTOR_TYPE_SAMPLER

### ISSUE THREAD

**Issue by Tom-Olsen** [KhronosGroup/SPIRV-Reflect#281]
I am using an .hlsl fragment shader with a Texture2D and a SamplerState both in the same binding:

```
Texture2D texture : register(t1);
SamplerState samplerState : register(s1);
```

This is detected by SPIRV-Reflect as two separate descriptor set layouts with the same binding.
Example output from my code:

```
binding_count: 2
        spirv_id:        5
        name:            texture
        binding:         1
        descriptor_type: 2 = VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE
        descriptorCount: 1

        spirv_id:        7
        name:            samplerState
        binding:         2
        descriptor_type: 0 = VK_DESCRIPTOR_TYPE_SAMPLER
        descriptorCount: 1
```
        
I think it would make more sense to detect this as a single binding with the descriptor_type: 1 = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER.

**Comment by Tom-Olsen** [comment]
You're making a good point. I have to think a little bit more about it. But for now the information you asked for.
The complete fragment shader is:

```
Texture2D texture : register(t1);
SamplerState samplerState : register(s1);

struct FragmentInput
{
    float4 vertexColor : COLOR;
    float4 uv : TEXCOORD0;
};

float4 main(FragmentInput input) : SV_TARGET
{
    float4 color = texture.Sample(samplerState, input.uv.xy);
    return color;
}
```

and here a link to the compiled .spv:
https://www.dropbox.com/scl/fi/dulxtgyq9nkw3fvkfqg5i/triangleFrag.spv?rlkey=ifa560tiz3jkqvh3ysfbyfl1d&st=qt7fc4rx&dl=0

**Comment by spencer-lunarg** [comment]
https://godbolt.org/z/eE7zhd7r7

so the issue is the SPIR-V is using a `OpSampledImage`

```swift
%24 = OpSampledImage %type_sampled_image %21 %22
%25 = OpImageSampleImplicitLod %v4float %24 %23 None
```

when using a Combined Image Sampler, you would do the `OpImageSampleExplicitLod` directly to a `OpTypeSampledImage` pointer (yes, this starts to get confusing quick with similar names)

There is nice write up in the Vulkan Guide about this  (https://github.com/KhronosGroup/Vulkan-Guide/blob/main/chapters/mapping_data_to_shaders.adoc#combined-image-sampler)

but to my knowledge, for HLSL, this not intended to be `VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER` and GLSL has a dedicated `sampler2D` for this

**Comment by Tom-Olsen** [comment]
ok thanks, I will have a closer look at it tomorrow.
Im closing the issue.
