### ISSUE TITLE
Why the maximum descriptor set number is a fixed value?

### ISSUE THREAD

**Issue by PENGUINLIONG** [KhronosGroup/SPIRV-Reflect#76]
Is there any specific reason for that? Just wondering.

**Comment by chaoticbob** [comment]
Good question. There's two "reasons" - in quotes because they're more practically driven than based on a spec.

First reason - among the GPUs surveyed for Vulkan at that time, there was a maximum bound descriptor set of 32. The logic behind this was that a shader most likely wouldn't have more than 32 descriptor sets - so 64 was selected to make sure there's room in case 32 was exceeded. 

Second reason - at the time it was to minimize allocations. However as it turns out, there's plenty of other allocations happening that could've amortized this one.

**Comment by PENGUINLIONG** [comment]
Thanks for the reply
